//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: amm
// ----------------------------------------------------------------------------
pub mod amm {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for amm
    pub fn program_id() -> Pubkey {
        pubkey!("92NnZLZ8TS5Ay1UwAnQmtbYWbAFcEWtZcn7MwVkLhhMZ")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CreateLiquidityPool
    // ....................................................................

    /// Main instruction struct for CreateLiquidityPool
    pub struct CreateLiquidityPoolInstruction {
        pub accounts: CreateLiquidityPoolInstructionAccountMetas,
        pub data: CreateLiquidityPoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateLiquidityPool instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateLiquidityPoolInstructionAccountMetas {
        pub creator: AccountMeta,

        pub global_config: AccountMeta,

        pub liquidity_pool: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub lp_mint: AccountMeta,

        pub mint_a_vault: AccountMeta,

        pub mint_b_vault: AccountMeta,

        pub lp_mint_vault: AccountMeta,

        pub creator_a_ata: AccountMeta,

        pub creator_b_ata: AccountMeta,

        pub creator_lp_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateLiquidityPool instruction
    #[derive(Debug, Clone)]
    pub struct CreateLiquidityPoolInstructionAccounts {
        pub creator: Pubkey,

        pub global_config: Pubkey,

        pub liquidity_pool: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub lp_mint: Pubkey,

        pub mint_a_vault: Pubkey,

        pub mint_b_vault: Pubkey,

        pub lp_mint_vault: Pubkey,

        pub creator_a_ata: Pubkey,

        pub creator_b_ata: Pubkey,

        pub creator_lp_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl CreateLiquidityPoolInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            global_config: Pubkey,

            liquidity_pool: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            lp_mint: Pubkey,

            mint_a_vault: Pubkey,

            mint_b_vault: Pubkey,

            lp_mint_vault: Pubkey,

            creator_a_ata: Pubkey,

            creator_b_ata: Pubkey,

            creator_lp_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                creator,

                global_config,

                liquidity_pool,

                mint_a,

                mint_b,

                lp_mint,

                mint_a_vault,

                mint_b_vault,

                lp_mint_vault,

                creator_a_ata,

                creator_b_ata,

                creator_lp_ata,

                token_program,
            }
        }
    }

    /// Instruction data for CreateLiquidityPool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateLiquidityPoolInstructionData {
        pub amount_a: u64,

        pub amount_b: u64,
    }

    impl CreateLiquidityPoolInstructionData {
        pub fn new(amount_a: u64, amount_b: u64) -> Self {
            Self { amount_a, amount_b }
        }
    }

    /// Implementation for CreateLiquidityPoolInstruction
    impl CreateLiquidityPoolInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 75u8, 181u8, 165u8, 224u8, 254u8, 6u8, 131u8]
        }

        pub fn data(data: CreateLiquidityPoolInstructionData) -> Self {
            Self {
                accounts: CreateLiquidityPoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateLiquidityPoolInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.global_config = AccountMeta::new(accounts.global_config, false);

            self.accounts.liquidity_pool = AccountMeta::new(accounts.liquidity_pool, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.lp_mint = AccountMeta::new(accounts.lp_mint, false);

            self.accounts.mint_a_vault = AccountMeta::new(accounts.mint_a_vault, false);

            self.accounts.mint_b_vault = AccountMeta::new(accounts.mint_b_vault, false);

            self.accounts.lp_mint_vault = AccountMeta::new(accounts.lp_mint_vault, false);

            self.accounts.creator_a_ata = AccountMeta::new(accounts.creator_a_ata, false);

            self.accounts.creator_b_ata = AccountMeta::new(accounts.creator_b_ata, false);

            self.accounts.creator_lp_ata = AccountMeta::new(accounts.creator_lp_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.global_config.clone());

            metas.push(self.accounts.liquidity_pool.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.lp_mint.clone());

            metas.push(self.accounts.mint_a_vault.clone());

            metas.push(self.accounts.mint_b_vault.clone());

            metas.push(self.accounts.lp_mint_vault.clone());

            metas.push(self.accounts.creator_a_ata.clone());

            metas.push(self.accounts.creator_b_ata.clone());

            metas.push(self.accounts.creator_lp_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositLiquidity
    // ....................................................................

    /// Main instruction struct for DepositLiquidity
    pub struct DepositLiquidityInstruction {
        pub accounts: DepositLiquidityInstructionAccountMetas,
        pub data: DepositLiquidityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositLiquidity instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositLiquidityInstructionAccountMetas {
        pub provider: AccountMeta,

        pub liquidity_pool: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub lp_mint: AccountMeta,

        pub mint_a_vault: AccountMeta,

        pub mint_b_vault: AccountMeta,

        pub provider_a_ata: AccountMeta,

        pub provider_b_ata: AccountMeta,

        pub provider_lp_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for DepositLiquidity instruction
    #[derive(Debug, Clone)]
    pub struct DepositLiquidityInstructionAccounts {
        pub provider: Pubkey,

        pub liquidity_pool: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub lp_mint: Pubkey,

        pub mint_a_vault: Pubkey,

        pub mint_b_vault: Pubkey,

        pub provider_a_ata: Pubkey,

        pub provider_b_ata: Pubkey,

        pub provider_lp_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl DepositLiquidityInstructionAccounts {
        pub fn new(
            provider: Pubkey,

            liquidity_pool: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            lp_mint: Pubkey,

            mint_a_vault: Pubkey,

            mint_b_vault: Pubkey,

            provider_a_ata: Pubkey,

            provider_b_ata: Pubkey,

            provider_lp_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                provider,

                liquidity_pool,

                mint_a,

                mint_b,

                lp_mint,

                mint_a_vault,

                mint_b_vault,

                provider_a_ata,

                provider_b_ata,

                provider_lp_ata,

                token_program,
            }
        }
    }

    /// Instruction data for DepositLiquidity
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositLiquidityInstructionData {
        pub pool_id: u64,

        pub amount_a: u64,

        pub amount_b: u64,

        pub min_lp_out: u64,
    }

    impl DepositLiquidityInstructionData {
        pub fn new(pool_id: u64, amount_a: u64, amount_b: u64, min_lp_out: u64) -> Self {
            Self {
                pool_id,

                amount_a,

                amount_b,

                min_lp_out,
            }
        }
    }

    /// Implementation for DepositLiquidityInstruction
    impl DepositLiquidityInstruction {
        fn discriminator() -> [u8; 8] {
            [245u8, 99u8, 59u8, 25u8, 151u8, 71u8, 233u8, 249u8]
        }

        pub fn data(data: DepositLiquidityInstructionData) -> Self {
            Self {
                accounts: DepositLiquidityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositLiquidityInstructionAccounts) -> Self {
            self.accounts.provider = AccountMeta::new(accounts.provider, true);

            self.accounts.liquidity_pool = AccountMeta::new(accounts.liquidity_pool, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.lp_mint = AccountMeta::new(accounts.lp_mint, false);

            self.accounts.mint_a_vault = AccountMeta::new(accounts.mint_a_vault, false);

            self.accounts.mint_b_vault = AccountMeta::new(accounts.mint_b_vault, false);

            self.accounts.provider_a_ata = AccountMeta::new(accounts.provider_a_ata, false);

            self.accounts.provider_b_ata = AccountMeta::new(accounts.provider_b_ata, false);

            self.accounts.provider_lp_ata = AccountMeta::new(accounts.provider_lp_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.provider.clone());

            metas.push(self.accounts.liquidity_pool.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.lp_mint.clone());

            metas.push(self.accounts.mint_a_vault.clone());

            metas.push(self.accounts.mint_b_vault.clone());

            metas.push(self.accounts.provider_a_ata.clone());

            metas.push(self.accounts.provider_b_ata.clone());

            metas.push(self.accounts.provider_lp_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub global_config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub global_config: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(authority: Pubkey, global_config: Pubkey) -> Self {
            Self {
                authority,

                global_config,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub protocol_fee_bps: u16,

        pub fee_bps: u16,
    }

    impl InitializeInstructionData {
        pub fn new(protocol_fee_bps: u16, fee_bps: u16) -> Self {
            Self {
                protocol_fee_bps,

                fee_bps,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.global_config = AccountMeta::new(accounts.global_config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.global_config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RedeemLp
    // ....................................................................

    /// Main instruction struct for RedeemLp
    pub struct RedeemLpInstruction {
        pub accounts: RedeemLpInstructionAccountMetas,
        pub data: RedeemLpInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RedeemLp instruction
    #[derive(Debug, Clone, Default)]
    pub struct RedeemLpInstructionAccountMetas {
        pub redeemer: AccountMeta,

        pub liquidity_pool: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub lp_mint: AccountMeta,

        pub mint_a_vault: AccountMeta,

        pub mint_b_vault: AccountMeta,

        pub redeemer_a_ata: AccountMeta,

        pub redeemer_b_ata: AccountMeta,

        pub redeemer_lp_ata: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for RedeemLp instruction
    #[derive(Debug, Clone)]
    pub struct RedeemLpInstructionAccounts {
        pub redeemer: Pubkey,

        pub liquidity_pool: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub lp_mint: Pubkey,

        pub mint_a_vault: Pubkey,

        pub mint_b_vault: Pubkey,

        pub redeemer_a_ata: Pubkey,

        pub redeemer_b_ata: Pubkey,

        pub redeemer_lp_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl RedeemLpInstructionAccounts {
        pub fn new(
            redeemer: Pubkey,

            liquidity_pool: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            lp_mint: Pubkey,

            mint_a_vault: Pubkey,

            mint_b_vault: Pubkey,

            redeemer_a_ata: Pubkey,

            redeemer_b_ata: Pubkey,

            redeemer_lp_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                redeemer,

                liquidity_pool,

                mint_a,

                mint_b,

                lp_mint,

                mint_a_vault,

                mint_b_vault,

                redeemer_a_ata,

                redeemer_b_ata,

                redeemer_lp_ata,

                token_program,
            }
        }
    }

    /// Instruction data for RedeemLp
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RedeemLpInstructionData {
        pub pool_id: u64,

        pub lp_amount: u64,
    }

    impl RedeemLpInstructionData {
        pub fn new(pool_id: u64, lp_amount: u64) -> Self {
            Self { pool_id, lp_amount }
        }
    }

    /// Implementation for RedeemLpInstruction
    impl RedeemLpInstruction {
        fn discriminator() -> [u8; 8] {
            [12u8, 99u8, 190u8, 72u8, 228u8, 108u8, 109u8, 164u8]
        }

        pub fn data(data: RedeemLpInstructionData) -> Self {
            Self {
                accounts: RedeemLpInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RedeemLpInstructionAccounts) -> Self {
            self.accounts.redeemer = AccountMeta::new(accounts.redeemer, true);

            self.accounts.liquidity_pool = AccountMeta::new(accounts.liquidity_pool, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.lp_mint = AccountMeta::new(accounts.lp_mint, false);

            self.accounts.mint_a_vault = AccountMeta::new(accounts.mint_a_vault, false);

            self.accounts.mint_b_vault = AccountMeta::new(accounts.mint_b_vault, false);

            self.accounts.redeemer_a_ata = AccountMeta::new(accounts.redeemer_a_ata, false);

            self.accounts.redeemer_b_ata = AccountMeta::new(accounts.redeemer_b_ata, false);

            self.accounts.redeemer_lp_ata = AccountMeta::new(accounts.redeemer_lp_ata, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.redeemer.clone());

            metas.push(self.accounts.liquidity_pool.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.lp_mint.clone());

            metas.push(self.accounts.mint_a_vault.clone());

            metas.push(self.accounts.mint_b_vault.clone());

            metas.push(self.accounts.redeemer_a_ata.clone());

            metas.push(self.accounts.redeemer_b_ata.clone());

            metas.push(self.accounts.redeemer_lp_ata.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Swap
    // ....................................................................

    /// Main instruction struct for Swap
    pub struct SwapInstruction {
        pub accounts: SwapInstructionAccountMetas,
        pub data: SwapInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Swap instruction
    #[derive(Debug, Clone, Default)]
    pub struct SwapInstructionAccountMetas {
        pub signer: AccountMeta,

        pub liquidity_pool: AccountMeta,

        pub input_mint: AccountMeta,

        pub output_mint: AccountMeta,

        pub input_mint_vault: AccountMeta,

        pub output_mint_vault: AccountMeta,

        pub signer_input_ata: AccountMeta,

        pub signer_output_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Swap instruction
    #[derive(Debug, Clone)]
    pub struct SwapInstructionAccounts {
        pub signer: Pubkey,

        pub liquidity_pool: Pubkey,

        pub input_mint: Pubkey,

        pub output_mint: Pubkey,

        pub input_mint_vault: Pubkey,

        pub output_mint_vault: Pubkey,

        pub signer_input_ata: Pubkey,

        pub signer_output_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl SwapInstructionAccounts {
        pub fn new(
            signer: Pubkey,

            liquidity_pool: Pubkey,

            input_mint: Pubkey,

            output_mint: Pubkey,

            input_mint_vault: Pubkey,

            output_mint_vault: Pubkey,

            signer_input_ata: Pubkey,

            signer_output_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                signer,

                liquidity_pool,

                input_mint,

                output_mint,

                input_mint_vault,

                output_mint_vault,

                signer_input_ata,

                signer_output_ata,

                token_program,
            }
        }
    }

    /// Instruction data for Swap
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SwapInstructionData {
        pub pool_id: u64,

        pub params: SwapParams,

        pub slippage_limit: u64,
    }

    impl SwapInstructionData {
        pub fn new(pool_id: u64, params: SwapParams, slippage_limit: u64) -> Self {
            Self {
                pool_id,

                params,

                slippage_limit,
            }
        }
    }

    /// Implementation for SwapInstruction
    impl SwapInstruction {
        fn discriminator() -> [u8; 8] {
            [248u8, 198u8, 158u8, 145u8, 225u8, 117u8, 135u8, 200u8]
        }

        pub fn data(data: SwapInstructionData) -> Self {
            Self {
                accounts: SwapInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SwapInstructionAccounts) -> Self {
            self.accounts.signer = AccountMeta::new(accounts.signer, true);

            self.accounts.liquidity_pool = AccountMeta::new(accounts.liquidity_pool, false);

            self.accounts.input_mint = AccountMeta::new_readonly(accounts.input_mint, false);

            self.accounts.output_mint = AccountMeta::new_readonly(accounts.output_mint, false);

            self.accounts.input_mint_vault = AccountMeta::new(accounts.input_mint_vault, false);

            self.accounts.output_mint_vault = AccountMeta::new(accounts.output_mint_vault, false);

            self.accounts.signer_input_ata = AccountMeta::new(accounts.signer_input_ata, false);

            self.accounts.signer_output_ata = AccountMeta::new(accounts.signer_output_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.liquidity_pool.clone());

            metas.push(self.accounts.input_mint.clone());

            metas.push(self.accounts.output_mint.clone());

            metas.push(self.accounts.input_mint_vault.clone());

            metas.push(self.accounts.output_mint_vault.clone());

            metas.push(self.accounts.signer_input_ata.clone());

            metas.push(self.accounts.signer_output_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawProtocolFees
    // ....................................................................

    /// Main instruction struct for WithdrawProtocolFees
    pub struct WithdrawProtocolFeesInstruction {
        pub accounts: WithdrawProtocolFeesInstructionAccountMetas,
        pub data: WithdrawProtocolFeesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawProtocolFees instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawProtocolFeesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub global_config: AccountMeta,

        pub liquidity_pool: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub mint_a_vault: AccountMeta,

        pub mint_b_vault: AccountMeta,

        pub authority_a_ata: AccountMeta,

        pub authority_b_ata: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawProtocolFees instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawProtocolFeesInstructionAccounts {
        pub authority: Pubkey,

        pub global_config: Pubkey,

        pub liquidity_pool: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub mint_a_vault: Pubkey,

        pub mint_b_vault: Pubkey,

        pub authority_a_ata: Pubkey,

        pub authority_b_ata: Pubkey,

        pub token_program: Pubkey,
    }

    impl WithdrawProtocolFeesInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            global_config: Pubkey,

            liquidity_pool: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            mint_a_vault: Pubkey,

            mint_b_vault: Pubkey,

            authority_a_ata: Pubkey,

            authority_b_ata: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                global_config,

                liquidity_pool,

                mint_a,

                mint_b,

                mint_a_vault,

                mint_b_vault,

                authority_a_ata,

                authority_b_ata,

                token_program,
            }
        }
    }

    /// Instruction data for WithdrawProtocolFees
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawProtocolFeesInstructionData {
        pub pool_id: u64,
    }

    impl WithdrawProtocolFeesInstructionData {
        pub fn new(pool_id: u64) -> Self {
            Self { pool_id }
        }
    }

    /// Implementation for WithdrawProtocolFeesInstruction
    impl WithdrawProtocolFeesInstruction {
        fn discriminator() -> [u8; 8] {
            [11u8, 68u8, 165u8, 98u8, 18u8, 208u8, 134u8, 73u8]
        }

        pub fn data(data: WithdrawProtocolFeesInstructionData) -> Self {
            Self {
                accounts: WithdrawProtocolFeesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawProtocolFeesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.global_config = AccountMeta::new_readonly(accounts.global_config, false);

            self.accounts.liquidity_pool = AccountMeta::new(accounts.liquidity_pool, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.mint_a_vault = AccountMeta::new(accounts.mint_a_vault, false);

            self.accounts.mint_b_vault = AccountMeta::new(accounts.mint_b_vault, false);

            self.accounts.authority_a_ata = AccountMeta::new(accounts.authority_a_ata, false);

            self.accounts.authority_b_ata = AccountMeta::new(accounts.authority_b_ata, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.global_config.clone());

            metas.push(self.accounts.liquidity_pool.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.mint_a_vault.clone());

            metas.push(self.accounts.mint_b_vault.clone());

            metas.push(self.accounts.authority_a_ata.clone());

            metas.push(self.accounts.authority_b_ata.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: GlobalConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct GlobalConfig {
    pub authority: Pubkey,

    pub bump: u8,

    pub protocol_fee_bps: u16,

    pub fee_bps: u16,

    pub pool_count: u64,
}

impl GlobalConfig {
    pub fn new(
        authority: Pubkey,

        bump: u8,

        protocol_fee_bps: u16,

        fee_bps: u16,

        pool_count: u64,
    ) -> Self {
        Self {
            authority,

            bump,

            protocol_fee_bps,

            fee_bps,

            pool_count,
        }
    }
}

/// Custom struct: LiquidityPool
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LiquidityPool {
    pub creator: Pubkey,

    pub bump: u8,

    pub mint_a: Pubkey,

    pub mint_b: Pubkey,

    pub lp_mint: Pubkey,

    pub protocol_fee_bps: u16,

    pub fee_bps: u16,

    pub lp_supply: u64,

    pub amount_mint_a: u64,

    pub amount_mint_b: u64,

    pub accumulated_protocol_fee_a: u64,

    pub accumulated_protocol_fee_b: u64,
}

impl LiquidityPool {
    pub fn new(
        creator: Pubkey,

        bump: u8,

        mint_a: Pubkey,

        mint_b: Pubkey,

        lp_mint: Pubkey,

        protocol_fee_bps: u16,

        fee_bps: u16,

        lp_supply: u64,

        amount_mint_a: u64,

        amount_mint_b: u64,

        accumulated_protocol_fee_a: u64,

        accumulated_protocol_fee_b: u64,
    ) -> Self {
        Self {
            creator,

            bump,

            mint_a,

            mint_b,

            lp_mint,

            protocol_fee_bps,

            fee_bps,

            lp_supply,

            amount_mint_a,

            amount_mint_b,

            accumulated_protocol_fee_a,

            accumulated_protocol_fee_b,
        }
    }
}

/// Custom enum: SwapParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum SwapParams {
    ExactIn { input_amount: u64 },

    ExactOut { output_amount: u64 },
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
